  name: action runner controller test

  on:
    push:
      branches:
        - testing_actions

  jobs:
    build_test:
      runs-on: self-hosted

      steps:
        - name: Checkout code
          uses: actions/checkout@v2
