variable "cluster_name" {
    description = "EKS cluster name where the aws-load-balancer-controller will be installed."
    type        = string
}


variable "service_account_name" {
    description = "Name of the ServiceAccount to use for the controller. If empty and service_account_create=true, a name will be generated by Helm."
    type        = string
    default     = ""
}

variable "cluster_oidc_issuer_url" {
    description = "OIDC issuer URL for the EKS cluster, used for IRSA."
    type        = string
}


variable "aws_lb_controller_repository" {
  description = "Helm repository for AWS Load Balancer Controller"
  type        = string
  default     = "https://aws.github.io/eks-charts"
}

variable "aws_lb_controller_chart" {
  description = "Helm chart name for AWS Load Balancer Controller"
  type        = string
  default     = "aws-load-balancer-controller"
}

variable "aws_lb_controller_chart_version" {
  description = "Helm chart version for AWS Load Balancer Controller"
  type        = string
  default     = "1.10.1"
}


variable "aws_lb_controller_version" {
  description = "Version of the AWS Load Balancer Controller"
  type        = string
  default     = "v2.10.1"
}


variable "environment" {
  description = "The environment tag to apply to resources"
  type        = string
  default     = "dev"
}

