# Generated by Terragrunt. Sig: nIlQXj57tbuaRZEa
terraform {
  backend "s3" {
    bucket         = "terragrunt-aws-colocho86"
    dynamodb_table = "terraform-locks"
    encrypt        = true
    key            = "dev/test/terraform.tfstate"
    profile        = "personal"
    region         = "us-east-1"
  }
}
