# Generated by Terragrunt. Sig: nIlQXj57tbuaRZEa
provider "aws" {
  region = "us-east-1"
  profile = "personal"
  alias  = "aws1"
  assume_role {
    role_arn = "arn:aws:iam::734237051973:role/RolePowerUserAccess"
  }
}

provider "aws" {
  region = "us-east-1"
  alias  = "aws2"
  profile = "personal2"
  assume_role {
    role_arn = "arn:aws:iam::471112715935:role/RolePowerUserAccess"
  }
}
