name: demo-terragrunt

on:
  push:
    branches:
        - develop

jobs:
  init:
    runs-on: ubuntu-latest

    steps:
    - name: Pull code
      uses: actions/checkout@v2

    - name: List files
      run: ls -ls
      working-directory: '/home/runner/work/terragrunt-aws-eks/terragrunt-aws-eks/live/dev/test'
