name: demo-terragrunt

on:
  push:
    branches:
        - develop

jobs:
  init:
    runs-on: ubuntu-latest

    steps:
    - name: Pull code
      uses: actions/checkout@v2

    - name: List files
      run: ls -ls
      working-directory: '/home/runner/work/terragrunt-aws-eks/terragrunt-aws-eks/live/dev/test'

    - name: Configure AWS credentials
      uses: aws-actions/configure-aws-credentials@v4
      with:
        aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID_ACCOUNT_ONE }}
        aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY_ACCOUNT_ONE }}
        aws-region: us-east-1
        role-to-assume: ${{ secrets.CROSS_ACCOUNT }}
        role-duration-seconds: 901
        role-skip-session-tagging: true
    - name: Prerequisite Instalation
      run: |
        sudo npm install -g aws-cdk@1.31.0
        cdk --version
        aws s3 ls
