name: demo-terragrunt

on:
  push:
    branches:
        - develop
env:
  tf_version: '1.7.5'
  tg_version: '0.66.3'
  working_dir: '/home/runner/work/terragrunt-aws-eks/terragrunt-aws-eks/live/dev/test'
#   TF_PLUGIN_CACHE_DIR: ${{ github.workspace }}/.terraform.d/plugin-cache

jobs:
  plan_apply:
    runs-on: ubuntu-latest

    steps:
    - name: Pull code
      uses: actions/checkout@main

    - name: List files
      run: ls -ls
      working-directory: '/home/runner/work/terragrunt-aws-eks/terragrunt-aws-eks/live/dev/test'

    - name: Configure AWS credentials
      uses: aws-actions/configure-aws-credentials@v4
      with:
        aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID_ACCOUNT_ONE }}
        aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY_ACCOUNT_ONE }}
        aws-region: us-east-1
        role-to-assume: ${{ secrets.CROSS_ACCOUNT }}
        role-duration-seconds: 901
        # role-skip-session-tagging: true
    - name: Prerequisite Instalation
      run: |
        sudo npm install -g aws-cdk@1.31.0
        cdk --version
        aws s3 ls

    # - name: Create terraform plugin cache dir
    #   run: mkdir -p  $TF_PLUGIN_CACHE_DIR

    # - name: Terraform Plugin Cache
    #   uses: actions/cache@v4.0.1
    #   with:
    #     path: ${{ env.TF_PLUGIN_CACHE_DIR }}
    #     key: ${{ runner.os }}-terraform-plugin-cache-${{ hashFiles('**/.terraform.lock.hcl') }}

    - name: Check terragrunt HCL
      uses: gruntwork-io/terragrunt-action@v2
      with:
        tf_version: ${{ env.tf_version }}
        tg_version: ${{ env.tg_version }}
        tg_dir: ${{ env.working_dir }}
        tg_command: 'hclfmt --terragrunt-check --terragrunt-diff'

    - name: Plan
      uses: gruntwork-io/terragrunt-action@v2
      with:
        tf_version: ${{ env.tf_version }}
        tg_version: ${{ env.tg_version }}
        tg_dir: ${{ env.working_dir }}
        tg_command: 'plan'

    - name: Apply Changes
      uses: gruntwork-io/terragrunt-action@v2
      with:
        tf_version: ${{ env.tf_version }}
        tg_version: ${{ env.tg_version }}
        tg_dir: ${{ env.working_dir }}
        tg_command: 'apply'

